### ISSUE TITLE
setTimeout and Chrome

### ISSUE THREAD

**Issue by meilon** [straubr/TTO-Timer#1]
Hi!
We love the addon, helps us a lot. But there is one issue for our chrome users: When the tab with the timer is inactive, Chrome slows down the JS execution and therefore displays a wrong elapsed time: http://stackoverflow.com/questions/6032429/chrome-timeouts-interval-suspended-in-background-tabs
A quick test showed that in a minute on another tab showed only 30 elapsed seconds.

There are two solutions: Either set the current Date() on start and subtract that from the current Date() every second (would mean very accurate time) or use Web Workers. I think the first method would be easier to implement.

**Comment by straubr** [comment]
Oh wow, I never noticed this.

This means all the time I relied on my own addon I wrote down the incorrect times... bleh.

I'll look into this the next days. Glad you like the addon!

**Comment by straubr** [comment]
Should be fixed now. Thank you again for pointing this out. I'll upload the new .opm to OPAR soon.
