### ISSUE TITLE
Feature Request: Add TTO-Timer to AgentTicketPhone

### ISSUE THREAD

**Issue by meilon** [straubr/TTO-Timer#2]
Would it be an option to make it configurable that TTO-Timer could appear in AgentTicketPhone and maybe AgentTicketEmail? If someone calls in and you start a remote session right away, those minutes should be logged, too. Clicking on the timer in these two views should cause the current time to be entered into the time field.

**Comment by straubr** [comment]
Hey there, sure that should (have been) easily possible but I had a hardcoded check for the template in the module. I just pushed a new version (5.0.6) to git and OPAR. With that version you can configure the views where you want that timer. Just navigate in the SysConfig to:
TTO Framework -> Frontend::Agent::ModuleRegistration

and add the Actions to the "Templates" entry of the module. Please be aware that clicking on the timer will fails as in the view "AgentTicketPhone" or "AgentTicketEmail" the ticket isn't yet created, thus a note can't be appended.
