### ISSUE TITLE
Compatibility with OTRS 6

### ISSUE THREAD

**Issue by meilon** [straubr/TTO-Timer#3]
Hi there,

we'd like to update to OTRS 6 now that Patch Level 2 is out, is a compatibility upgrade of TTO-Timer planned?

**Comment by straubr** [comment]
Hey Meilon,

First: I'm glad that this addon is used - thanks for that ;)

Second: Upgrading this (and other packages) is definitely planned. It probably will happen early 2018 as we are currently busy with an office move.

Cheers and best regards,
Rolf

**Comment by straubr** [comment]
Package is migrated - see branch v6.x for the new sources. The .opm is uploaded to opar:
https://opar.perl-services.de/dist/TTO-Timer-6.0.0

Package was successfully tested on Ubuntu 16 with OTRS 6.0.3.

Please let me know if there are any problems.
